### ISSUE TITLE
Update the directory structure as per PEP 503 guidelines

### ISSUE THREAD

**Issue by harshad16** [thoth-station/httpd-aicoe-container#2]
The pip and pipenv require a directory structure for the wheel files as `distribution/configuration/simple/tensorflow/tensorflow.whl#sha`, otherwise, they refuse to install these packages.

Reference: [PEP 503 guidelines](https://www.python.org/dev/peps/pep-0503/)

**Comment by sub-mod** [comment]
Also needs a small test.sh script to create pipenv and test if `pip install` works.
