### ISSUE TITLE
Issue in installing wheels from manylinux2010 index

### ISSUE THREAD

**Issue by harshad16** [thoth-station/httpd-aicoe-container#20]
**Describe the bug**
Unable to install Tensorflow wheels from https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/jemalloc/simple/ index via pipenv.

**To Reproduce**
Usually, we have a custom Pipfile to install Red Hat AICoE custom Tensorflow wheels.
```
[[source]]
url ="https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/jemalloc/simple/"
verify_ssl = true
name = "redhat-aicoe-experiments"

[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[requires]
python_version = "3.6"

[packages]
tensorflow = {version="==1.13.2", index="redhat-aicoe-experiments"}

[pipenv]
allow_prereleases = true
```
When we install packages, by executing `pipenv install` the packages are installed and the TensorFlow from redhat-aicoe would be installed. we can check that by executing following command `pip3 show tensorflow | grep Author` in the virtual environment.

**Expected behavior**
Successfully installing tensorflow and show Red Hat in author when executed following command `pip3 show tensorflow | grep Author` in the virtual environment.

**Additional context**
May be the issue is in the wheel files, unsure.

**Comment by harshad16** [comment]
The issue is resolved, As after talking to @sub-mod, I got to know that the manylinux2010 wheels released were not in name of Red Hat AICoE. Hence, installing the wheels from the AICoE index would result in receiving the  manylinux2010 wheels built by Red Hat AICoE but the author still remaining Google.

**Comment by goern** [comment]
Shall we indicate we are the publisher? Or what is the rational why it's still work Google's name?

**Comment by fridex** [comment]
I think it's due to the design of [python indexes](https://thoth-station.ninja/docs/developers/adviser/provenance_checks.html#error-artifact-different-source) where they are treated as mirrors. Also, the builds that Subin is producing should have RH as publisher set - at least we relly on that in some parts of Thoth.
