### ISSUE TITLE
Adjust Tensorflow Index page according to PEP 503 standards 

### ISSUE THREAD

**Issue by harshad16** [thoth-station/httpd-aicoe-container#28]
Adjust the maintained AICoE TensorFlow index according to PEP 503 standards so that the index is in compliance and isn't violating PEP standards.

**Reference**
https://github.com/brettcannon/mousebender/issues/19
https://www.python.org/dev/peps/pep-0503/
https://twitter.com/fridex/status/1248662679985836032
https://packaging.python.org/guides/hosting-your-own-index/
https://devpi.net/docs/devpi/devpi/latest/%2Bd/index.html
https://httpd.apache.org/docs/trunk/urlmapping.html
http://httpd.apache.org/docs/trunk/mod/mod_dir.html#directoryindex

**Comment by fridex** [comment]
thx :wink:

**Comment by goern** [comment]
is this still valid?

**Comment by fridex** [comment]
Superseded by https://github.com/thoth-station/thoth-application/issues/1013
