### ISSUE TITLE
Need Admin Access

### ISSUE THREAD

**Issue by sub-mod** [thoth-station/httpd-aicoe-container#5]
@harshad16 can you please add me as admin user.And also the owner of the repo.
We cannot do few admin actions on the repo if we don't have atleast one of the active developers in the Thoth Project as owner of this repo.

**Comment by harshad16** [comment]
@sub-mod Even I don't have the admin access.
@goern  and @fridex  PTAL at this issue.

**Comment by goern** [comment]
looks like done. fridex and I as org owners are owners of each repo anyway, so we wouldnt loose any access or so...
