### ISSUE TITLE
Need Admin Access

### ISSUE THREAD

**Issue by sub-mod** [thoth-station/httpd-aicoe-container#6]
Based on this https://github.com/thoth-station/httpd-aicoe-container/issues/5
@goern @fridex Can you add me to the Admin/Owner list for this specific repo ONLY.

<img width="1046" alt="screen shot 2018-08-28 at 4 36 27 pm" src="https://user-images.githubusercontent.com/7363264/44749480-1bd49100-ab02-11e8-8482-26e789a4ebe7.png">

**Comment by goern** [comment]
I cant understand what you need, you have write access. Can you specify re access rights required?

**Comment by sub-mod** [comment]
This shouldn't be a complicated request.I want the flexibility to add webhooks or watever. I don't wish to connect with anyone for any access in the future.

**Comment by sub-mod** [comment]
Thanks
